## Data Science
La ciencia de datos o Data Science es una interdisciplina que busca aplicar los metodos matematicos y computacionales al analisis de los datos (especialmente en grandes volumenes) de tal manera que pueda extraerse mejor informacion de estos. Asi, un cientifico de datos debe tener habilidades en matematicas, estadistica y computacion, ademas del conocimiento experto en el area de donde provienen los datos, que le permita no solo analizar los datos sino ademas tomar decisiones relevantes en base a estos. Una gran ventaja es que muchas de las tecnicas matematicas que pueden ayudar en el manejo de los datos estan implementadas en varias librerias de Python.

## La libreria NumPy
Numpy es un paquete fundamental para computacion cientifica, que puede fuencionar como contenedor multidimensional de datos genericos con bastante eficiencia. Contiene muchas herramientas del algebra lineal, transformadas, generadores de numeros aleatorios, herramientas para integrar C,C++, Fortran, entre otras cosas. Las herramientas de NumPy son por lo general bastante rapidas, pues estan basadas en las librerias de lenguaje C.

### Los arreglos de NumPy

La funcionalidad mas comun de NumPy son los arreglos. De manera sencilla, los arreglos son la representacion de las matrices del algebra lineal.

In [4]:
# Para llamar a la libreria se usa import
# Se puede agregar un atajo para llamarla mas adelante
import numpy as np

In [5]:
# Se puede construir un arreglo a partir de una lista
l1=[1,2,3]
# Para construir un arreglo se usa la funcion array
A=np.array(l1)
A

array([1, 2, 3])

In [6]:
# La lista para construir el arreglo se puede escribir dentro 
# del llamado de la funcion
B=np.array([[2,3],[4,5]])
B

array([[2, 3],
       [4, 5]])

Cada lista que se pasa dentro de los parametros se toma como una fila de la matriz. Tambien se pueden construir arreglos de manera secuencial, usando la funcion arange()

In [8]:
# La funcion arange tiene tres parametros: un valor de inicio,
# un valor limite y un tamaño de paso. El valor limite se omite
np.arange(2,100,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

Tambien se pueden construir arreglos de ceros y unos

In [9]:
# la funcion zeros pide un argumento de forma para el 
# tamaño del arreglo, que se pasa como una tupla
print(np.zeros((2,3,4)))

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]

In [ ]:
# Funciona igual para la funcion ones()
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Tambien existe la funcion linspace(), que genera un vector con una particion entre dos puntos, con un numero fijo de puntos, o la funcion eye() que crea una matriz identidad

In [ ]:
# los argumentos de linspace son valor inicial, valor final, numero de puntos
np.linspace(3,8,10)

array([3.        , 3.55555556, 4.11111111, 4.66666667, 5.22222222,
       5.77777778, 6.33333333, 6.88888889, 7.44444444, 8.        ])

In [ ]:
# eye solo lleva un argumento, pues las matrices identidad son cuadradas
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Tambien se pueden generar matrices de numeros aleatorios, con las funciones rand(), randn(), randint(). estas estan dentro de la sublibreria random().

In [11]:
# La funcion rand genera numeros aleatorios entre 0 y 1
print(np.random.rand(5,2))
# randn genera numeros aleatorios basados en una normal estandar.
print(np.random.randn(2,3))
# randint genera numeros enteros de manera aleatoria con tres parametros,
# valor inicial, valor final, numero de elementos. El valor final
# se omite.
print(np.random.randint(-2,2,(2,3)))

[[0.30307743 0.04494112]
 [0.91574393 0.79991057]
 [0.42837642 0.485837  ]
 [0.48392705 0.32837417]
 [0.4379446  0.23212427]]
[[-0.66495789  0.18257281  1.09356944]
 [ 0.93265459  0.01437635  0.39254155]]
[[-2  0  0]
 [-1 -2  1]]

Los arreglos tiene varios atributos, que son pequeñas funciones preconstruidas con el arreglo.

In [ ]:
# shape devuelve el tamaño del arreglo
A=np.array([[2,3,1,4,5],[5,1,-2,3,3]])
A.shape

(2, 5)

In [ ]:
# reshape() reacomoda el arreglo a una nueva forma. 
# Es necesario que tenga el mismo numero de elementos.
print(A)
print(A.reshape((5,2)))

[[ 2  3  1  4  5]
 [ 5  1 -2  3  3]]
[[ 2  3]
 [ 1  4]
 [ 5  5]
 [ 1 -2]
 [ 3  3]]

In [ ]:
# Para buscar un valor maximo o minimo
print(A.max(),A.min())
# Para buscar los indices de dichos valores
print(A.argmax(),A.argmin())

5 -2
4 7

Es posible buscar elementos particulares de un arreglo usando los indices de posicion. Para llamar un indice se usan []

In [ ]:
# Para llamar a la primera fila del arreglo
print(A[0])
# Para llamar al segundo elemento en la primera fila
print(A[0][1])

[2 3 1 4 5]
3

Es posible tambien modificar valores especificos del arreglo, o todo un rango de indices

In [ ]:
print(A)
# Cambiando un valor del arreglo
A[0][1]=-5
print(A)
# Cambiando toda la primera fila 
A[0]=0
print(A)
# Cambiando todos los elementos de la primera fila,
# menos el primero
A[0][1:]=-3
print(A)

[[ 2  3  1  4  5]
 [ 5  1 -2  3  3]]
[[ 2 -5  1  4  5]
 [ 5  1 -2  3  3]]
[[ 0  0  0  0  0]
 [ 5  1 -2  3  3]]
[[ 0 -3 -3 -3 -3]
 [ 5  1 -2  3  3]]

Es importante anotar que salvo que se cree de manera explicita, no se generan copias de las variables en Python, solo atajos. Esto permite ahorrar memoria.

In [ ]:
A=np.array([1,2,3])
print(A)
B=A
B[0]=0
print(A)

[1 2 3]
[0 2 3]

Se pueden efectuar operaciones sobre todo el arreglo: las algebraicas son matriciales, pero tambien se pueden efectuar operaciones booleanas y de operadores.

In [ ]:
print(A==0)
print(A[A%2==0])

[ True False False]
[0 2]

In [12]:
# Las operaciones algebraicas son similares a las operaciones con matrices
# que se realizan componente a componente.
A=np.random.randint(-10,10,(2,3))
print(A)
print(A+A)
print(2*A)
print(A*A)
# Las funciones universales dentro de NumPy tambien se pueden aplicar a arreglos
print(np.sin(A))

[[  1   3   3]
 [ -6 -10   9]]
[[  2   6   6]
 [-12 -20  18]]
[[  2   6   6]
 [-12 -20  18]]
[[  1   9   9]
 [ 36 100  81]]
[[0.84147098 0.14112001 0.14112001]
 [0.2794155  0.54402111 0.41211849]]

In [ ]:
# Para transponer el arreglo, transpose()
# Para multiplicar matrices, matmul()
np.matmul(A,np.transpose(A))

array([[ 66, -49],
       [-49, 113]])

In [ ]:
# El arreglo es un objeto iterable. 
# Por defecto se itera por filas
for i in A:
  print(i)

[-4 -5  5]
[-4  4 -9]

In [ ]:
# Es posible "aplanar" el arreglo
for i in A.flat:
  print(i)

-4
-5
5
-4
4
-9

Aunque quiza la operacion que mas se recuerda cuando se habla de matrices son los sistemas de ecuaciones y las operaciones del algebra lineal. NumPy tiene una libreria dedica al algebra lineal, linalg. Dentro de esta se puede usar solve() para solucionar sistemas de ecuaciones, siempre que la matriz de coeficientes sea cuadrada e invertible.

In [ ]:
A=np.random.randint(-3,3,(2,2))
b=np.random.randint(-3,3,(2,1))
np.linalg.solve(A,b)

array([[-0.8],
       [-0.4]])

In [ ]:
np.mean(A)

-0.25

## SymPy
El paquete Sympy es un paquete de calculo de algebra simbolica. Permite realizar operaciones con objetos matematicos, como factorizaciones, limites, derivadas, integrales, etc.

In [ ]:
# Si se calcula una raiz cuadrada con el paquete math
import math
math.sqrt(8)

2.8284271247461903

In [13]:
# La raiz cuadrada de 8 es un numero irracional, asi que al 
# pedir una raiz cuadrada se obtiene una aproximacion. 
# Si se ejecuta el mismo calculo en SymPy
import sympy
sympy.sqrt(8)

2*sqrt(2)

SymPy puede trabajar con variables de manera abstracta como se hace en matematicas. Se definen como objetos simbolos

In [ ]:
from sympy import Symbol
x=Symbol('x')
y=Symbol('y')
pol=x**2-2*x*y+y**2
pol

x**2 - 2*x*y + y**2

In [ ]:
from sympy import factor, expand
factor(pol)

(x - y)**2

Con los simbolos se pueden realizar muchos procesos del calculo de manera automatica

In [ ]:
from sympy import *
# Una derivada
diff(sin(x**2))

2*x*cos(x**2)

In [ ]:
# una integral
integrate((x)/(x**2+1),x)

log(x**2 + 1)/2

In [ ]:
# un limite
limit((x**2-1)/(x-1),x,1)

2

In [ ]:
# buscar raices de polinomios
solve(x**2-2*x-5,x)

[1 - sqrt(6), 1 + sqrt(6)]

La documentacion de SymPy es extensa, y abarca procesos en muchas areas, desde el calculo a la teoria de categorias, la combinatoria, ecuaciones diferenciales, geometria, fisica, etc. Es una muestra de lo versatil que puede llegar a ser un lenguaje de programacion

## Pandas
Una de las librerias mas populares para trabajar con datos, Pandas permite realizar analisis de datos de forma eficiente, ejecutar tareas de limpieza y preprocesamiento, visualizaciones, etc. Esta construida sobre NumPy y en algunos casos se considera una version muy potente de Excel, aunque Pandas posee muchas mas caracteristicas.

Pandas puede definir dos objetos basicos: las series y los DataFrames. Una serie es similar a un arreglo de NumPy donde ademas de los indices se pueden usar etiquetas para determinar la posicion de un objeto sobre la serie. Puede ademas contener cualquier objeto de Python.

In [15]:
# Para importar Pandas
import pandas as pd

In [ ]:
# Para crear una serie, puede usarse la funcion Series
s=pd.Series(data=[2,3,4])
s

0    2
1    3
2    4
dtype: int64

Sin un conjunto de etiquetas, se asignan etiquetas numericas similares a una indexacion usual.

In [16]:
s=pd.Series(data=[2,3,4],index=['a','b','c'])
s

a    2
b    3
c    4
dtype: int64

In [ ]:
s['a']

2

Pueden crearse series a partir de arreglos o diccionarios, tambien. La serie puede almacenar cualquier dato, incluso funciones.

In [17]:
s=pd.Series(data=[2,len,4])
s

0                          2
1    <built-in function len>
2                          4
dtype: object

A partir de las series es posible revisar los DataFrames. Es posible pensar en un DataFrame como un conjunto de series (columnas) que comparten los mismos indices. Los DataFrame estan inspirados en un objeto del lenguaje R y son la herramienta mas comun en Python para trabajar con bases de datos.

In [18]:
# Para llamar la libreria
import pandas as pd

In [19]:
# Un dataframe requiere al menos de un arreglo como parametro. 
# Pueden agregarse indices y nombres de columnas, pues el dataframe 
# tiene una estructura similar a una matriz.
df=pd.DataFrame(np.random.randn(5,5),index=['A','B','C','D','E'],columns=['col1','col2','col3','col4','col5'])

In [20]:
df

       col1      col2      col3      col4      col5
A -0.632909 -0.789612  1.482843 -1.019152 -0.488237
B  0.289136  2.417740  0.040001  0.745129  0.013595
C -1.015240  0.311009  0.919626 -1.264921  1.418855
D -0.849468  2.204861  1.081898 -0.338185 -0.752088
E -1.420443  1.799351  0.498167 -2.039857  0.048715

In [21]:
# Se puede hacer un llamado a una columna usando su nombre
df['col1']

A   -0.632909
B    0.289136
C   -1.015240
D   -0.849468
E   -1.420443
Name: col1, dtype: float64

In [ ]:
type(df['col1'])

pandas.core.series.Series

In [23]:
# Se pueden construir columnas nuevas a partir de columnas ya existentes o de datos nuevos
df['col6']=df['col1']**2
df

       col1      col2      col3      col4      col5      col6
A -0.632909 -0.789612  1.482843 -1.019152 -0.488237  0.400573
B  0.289136  2.417740  0.040001  0.745129  0.013595  0.083600
C -1.015240  0.311009  0.919626 -1.264921  1.418855  1.030712
D -0.849468  2.204861  1.081898 -0.338185 -0.752088  0.721596
E -1.420443  1.799351  0.498167 -2.039857  0.048715  2.017657

In [24]:
# Tambien es posible quitar columnas del arreglo
df.drop('col6',axis=1,inplace=True) 
# axis indica si se trabaja en filas (0) o columnas (1)
# inplace indica si el cambio modifica o no el dataframe
df

       col1      col2      col3      col4      col5
A -0.632909 -0.789612  1.482843 -1.019152 -0.488237
B  0.289136  2.417740  0.040001  0.745129  0.013595
C -1.015240  0.311009  0.919626 -1.264921  1.418855
D -0.849468  2.204861  1.081898 -0.338185 -0.752088
E -1.420443  1.799351  0.498167 -2.039857  0.048715

In [25]:
# Las filas tambien pueden ser llamadas,
# con el comando loc si se usa la etiqueta del indice
# o con el comando iloc si se usa la posicion.
print(df.loc['A'])
print(df.iloc[0])

col1   -0.632909
col2   -0.789612
col3    1.482843
col4   -1.019152
col5   -0.488237
Name: A, dtype: float64
col1   -0.632909
col2   -0.789612
col3    1.482843
col4   -1.019152
col5   -0.488237
Name: A, dtype: float64

In [26]:
# selecccionar varias columnas
df[['col1','col3']]

       col1      col3
A -0.632909  1.482843
B  0.289136  0.040001
C -1.015240  0.919626
D -0.849468  1.081898
E -1.420443  0.498167

Se pueden realizar operaciones sobre las columnas o filas del dataframe, algunas propias de Pandas.

In [27]:
# Para calcular el promedio de una columna
df['col1'].mean()

-0.7257846756792906

Esta funcion estadistica tambien se puede obtener, junto a otros indicadores utiles, por medio del metodo describe

In [28]:
df.describe()

           col1      col2      col3      col4      col5
count  5.000000  5.000000  5.000000  5.000000  5.000000
mean  -0.725785  1.188670  0.804507 -0.783397  0.048168
std    0.636459  1.378412  0.554223  1.048897  0.837872
min   -1.420443 -0.789612  0.040001 -2.039857 -0.752088
25%   -1.015240  0.311009  0.498167 -1.264921 -0.488237
50%   -0.849468  1.799351  0.919626 -1.019152  0.013595
75%   -0.632909  2.204861  1.081898 -0.338185  0.048715
max    0.289136  2.417740  1.482843  0.745129  1.418855

Al igual que NumPy, se pueden usar condicionales logicos para buscar datos.

In [33]:
df>0

    col1   col2  col3   col4   col5
A  False  False  True  False  False
B   True   True  True   True   True
C  False   True  True  False   True
D  False   True  True  False  False
E  False   True  True  False   True

In [31]:
df[df>0]

       col1      col2      col3      col4      col5
A       NaN       NaN  1.482843       NaN       NaN
B  0.289136  2.417740  0.040001  0.745129  0.013595
C       NaN  0.311009  0.919626       NaN  1.418855
D       NaN  2.204861  1.081898       NaN       NaN
E       NaN  1.799351  0.498167       NaN  0.048715

Los registros faltantes se notan como NaN ('not a number'). Generalmente esos valores se retiran o se reemplazan.

In [32]:
# dropna() quita por defecto las filas con valores NaN. Se puede cambiar
# a columnas con un axis=1 y hacer el cambio permanente con un inplace=True
df[df>0].dropna()

       col1     col2      col3      col4      col5
B  0.289136  2.41774  0.040001  0.745129  0.013595

In [34]:
# Para cambiar un registro NaN por un valor, se usa fillna
df[df>0].fillna(value=0)

       col1      col2      col3      col4      col5
A  0.000000  0.000000  1.482843  0.000000  0.000000
B  0.289136  2.417740  0.040001  0.745129  0.013595
C  0.000000  0.311009  0.919626  0.000000  1.418855
D  0.000000  2.204861  1.081898  0.000000  0.000000
E  0.000000  1.799351  0.498167  0.000000  0.048715

Tambien se pueden buscar registros que cumplan diversas condiciones sobre las columnas

In [35]:
df[(df['col1']>1) & (df['col5']<0)]

Empty DataFrame
Columns: [col1, col2, col3, col4, col5]
Index: []

Pandas tambien soporta multi-indices, lo que permite guardar muchas series de datos en un mismo dataframe

In [36]:
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

             A         B
G1 1  0.616736  0.347890
   2  0.791163  1.017452
   3  1.342439 -0.508179
G2 1  0.230419 -0.008615
   2  0.562576  0.472901
   3  1.024779 -0.895909

Tambien se pueden realizar agrupaciones de datos basados en valores. Para esto se usa la funcion groupby.

In [38]:
# Se puede usar un diccionario para crear un dataframe
df=pd.DataFrame({'Sede':['Bogota','Bogota','Cali','Cali','Medellin','Medellin'],
                 'Alumno':['Juan','Andrea','Andrea','Carlos','Mario','Luis'],
                 'Edad':[18,21,25,17,20,21]})
df

       Sede  Alumno  Edad
0    Bogota    Juan    18
1    Bogota  Andrea    21
2      Cali  Andrea    25
3      Cali  Carlos    17
4  Medellin   Mario    20
5  Medellin    Luis    21

In [39]:
# Agrupemos por sede 
df.groupby('Sede')

La funcion groupby genera un objeto de pandas. Para sacar informacion se debe usar una funcion de agregacion (una funcion numerica que reduzca los datos de acuerdo a algun parametro)

In [40]:
df.groupby('Sede').mean()

          Edad
Sede
Bogota    19.5
Cali      21.0
Medellin  20.5

Notese que esta funcion de agregacion solo se ejecuta sobre la columna que tiene variables numericas. Distintas funciones generan diferentes resultados.

In [41]:
df.groupby('Sede').min()

          Alumno  Edad
Sede
Bogota    Andrea    18
Cali      Andrea    17
Medellin    Luis    20

Otra forma util de sacar informacion sobre el DataFrame son atributos

In [42]:
# informacion general del tipo de variables
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Sede    6 non-null      object
 1   Alumno  6 non-null      object
 2   Edad    6 non-null      int64
dtypes: int64(1), object(2)
memory usage: 272.0+ bytes

In [43]:
# los nombres de las columnas
df.columns

Index(['Sede', 'Alumno', 'Edad'], dtype='object')

In [44]:
# valores unicos de una columna
df['Sede'].unique()

array(['Bogota', 'Cali', 'Medellin'], dtype=object)

In [45]:
# Conteo de frecuencias
df['Sede'].value_counts()

Cali        2
Medellin    2
Bogota      2
Name: Sede, dtype: int64

Si se quiere aplicar alguna transformacion a los datos, se puede usar una funcion apply en composicion con otra funcion, o una expresion lambda

In [48]:
df['Edad'].apply(lambda x: x**2)

0    324
1    441
2    625
3    289
4    400
5    441
Name: Edad, dtype: int64

Se puede ordenar un dataframe de acuerdo a los valores de una columna

In [49]:
df.sort_values('Edad')

       Sede  Alumno  Edad
3      Cali  Carlos    17
0    Bogota    Juan    18
4  Medellin   Mario    20
1    Bogota  Andrea    21
5  Medellin    Luis    21
2      Cali  Andrea    25

Tambien pueden combinarse dataframe, usando principalmente tres metodos
* concat, que pega dos dataframes uno tras otro
* merge, que combina los dataframe a partir de valores comunes en las columnas
* join, que combina los dataframe a partir de valores comunes en los indices.

In [51]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

In [52]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7])

In [53]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [54]:
# Concatenar
pd.concat([df1,df2,df3])

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [57]:
izq = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
der = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})

In [58]:
# Fusionar 
pd.merge(izq,der,on='key')

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

merge tiene un argumento extra, how, que dice como se usan las claves de la fusion.

In [55]:
izq = pd.DataFrame({'key': ['K0', 'K1', 'K0', 'K0'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
der = pd.DataFrame({'key': ['K0', 'K0', 'K2', 'K2'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})

In [ ]:
pd.merge(izq,der,on='key',how='left')

  key   A   B    C    D
0  K0  A0  B0   C0   D0
1  K0  A0  B0   C1   D1
2  K1  A1  B1  NaN  NaN
3  K0  A2  B2   C0   D0
4  K0  A2  B2   C1   D1
5  K0  A3  B3   C0   D0
6  K0  A3  B3   C1   D1

De estas herramientas se puede ver la fuerza de Python para trabajar con bases de datos, con limpieza y recuperacion de informacion.